export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const FETCH_ARTICLES_TYPE = 'FETCH_ARTICLES_TYPE';

export const FETCH_ARTICLES_BY_TOPIC_REQUEST = 'FETCH_ARTICLES_BY_TOPIC_REQUEST';
export const FETCH_ARTICLES_BY_TOPIC_SUCCESS = 'FETCH_ARTICLES_BY_TOPIC_SUCCESS';
export const FETCH_ARTICLES_BY_TOPIC_ERROR = 'FETCH_ARTICLES_BY_TOPIC_ERROR';

export const VOTE_ARTICLE_REQUEST = 'VOTE_ARTICLE_REQUEST';
export const VOTE_ARTICLE_SUCCESS = 'VOTE_ARTICLE_SUCCESS';
export const VOTE_ARTICLE_ERROR = 'VOTE_ARTICLE_ERROR';
